### ISSUE TITLE
Improve UI of Fighter Screen

### ISSUE THREAD

**Issue by saiankit** [viralvaghela/git-fighter#3]
The fighter input screen looks simple. 
The UI could have been better on that screen. 
The fight button should be after the two inputs of the user.
It's intuitive that the Fight button should be after the two inputs. 
There should also be a note that the user should be adding a GitHub username

**Comment by saiankit** [comment]
I would love to work on this issue. Please assign this to me.

**Comment by viralvaghela** [comment]
Thanks, @saiankit Sure, go-ahead.
